all: 1/main 2/main 3/main 4/main

1/main: 1/main.c
	gcc 1/main.c -o 1/main -lm

2/main: 2/main.c
	gcc 2/main.c -o 2/main -lm

3/main: 3/main.c
	gcc 3/main.c -o 3/main -lm

4/main: 4/main.c
	gcc 4/main.c -o 4/main -lm

clean:
	rm -f 1/main 2/main 3/main 4/main
